# Generated by Django 4.2.6 on 2023-10-09 18:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("task_manager", "0002_remove_worker_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="worker",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="static/avatar"),
        ),
    ]
