# Generated by Django 4.2.6 on 2023-10-14 08:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("task_manager", "0003_worker_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="worker",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="media/static/avatar"
            ),
        ),
    ]
